version: '3'
services:
  db:
    image: mysql:5.7
    container_name: us-covimap-db
    restart: always
    ports:
      - "4401:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "!root!"
      MYSQL_DATABASE: covimap
      MYSQL_USER: usr_covimap
      MYSQL_PASSWORD: "pwd_covimap"

  scheduler:
    container_name: covimap-scheduler
    ports:
      - "7072:9000"
    environment:
      SWAGGER_PORT: 7072
      DEBUG: 0
      NODE_ENV: prdouction

    volumes:
      - ./scheduler/app:/app
    
    command: "npm run start"
    build:
      context: ./scheduler

  webapp:
    container_name: us-covimap-webapp
    ports:
      - "7071:9000"
    environment:
      DEBUG:0
      NODE_ENV: prdouction
      VIRTUAL_HOST: www.covimap.com
      LETSENCRYPT_HOST: www.covimap.com,covimap.com
      LETSENCRYPT_EMAIL: kevinthant@landzin.com
      VIRTUAL_PORT: 7071

    volumes:
      - ./webapp:/app
    command: "npm run start"
    build:
      context: ./webapp

networks:
  default:
    external:
      name: nginx-proxy

